export const comptes = [
    {
        id: 12341,
        role: "administrateur",
        identifiant: "administrateur",
        motDePasse: "administrateur",
        nom: "BONNIN",
        prenom: "Simon",
        email: "simon.bonnin@gmail.com",
    },
    {
        id: 12342,
        role: "restaurateur",
        identifiant: "prestataire1",
        motDePasse: "prestataire1",
        nom: "FULCRAND",
        prenom: "Lucas",
        email: "lucas.fulcrand@gmail.com",
    },
    {
        id: 12343,
        role: "createur",
        identifiant: "prestataire2",
        motDePasse: "prestataire2",
        nom: "GOUSSET",
        prenom: "Xavier",
        email: "xavier.gousset@gmail.com",
    },
    {
        id: 12344,
        role: "organisateur",
        identifiant: "prestataire3",
        motDePasse: "prestataire3",
        nom: "LANCON",
        prenom: "Johan",
        email: "johan.lancon@gmail.com",
    },
    {
        id: 12345,
        role: "vendeur",
        identifiant: "prestataire4",
        motDePasse: "prestataire4",
        nom: "GOUSSOT",
        prenom: "Théo",
        email: "theo.goussot@gmail.com",
    },
    {
        id: 12346,
        role: "utilisateur",
        identifiant: "utilisateur",
        motDePasse: "utilisateur",
        nom: "TEST",
        prenom: "Test",
        email: "test@gmail.com",
    },
    {
        id: 12347,
        role: "utilisateur",
        identifiant: "u2",
        motDePasse: "u2",
        nom: "u2",
        prenom: "u2",
        email: "u2.u2@example.com",
    },
    {
        id: 12348,
        role: "vendeur",
        identifiant: "v",
        motDePasse: "v",
        nom: "v",
        prenom: "v",
        email: "v.v@example.com",
    },
    {
        id: 12349,
        role: "createur",
        identifiant: "c",
        motDePasse: "c",
        nom: "c",
        prenom: "c",
        email: "c.c@example.com",
    },
    {
        id: 12350,
        role: "restaurateur",
        identifiant: "derya",
        motDePasse: "derya",
        nom: "Derya",
        prenom: "Derya",
        email: "derya.derya@example.com",
    },
    {
        id: 12351,
        role: "restaurateur",
        identifiant: "r3",
        motDePasse: "r3",
        nom: "Breizh Gaufres",
        prenom: "Breizh Gaufres",
        email: "breizh gaufres.breizh gaufres@example.com",
    },
    {
        id: 12352,
        role: "restaurateur",
        identifiant: "r4",
        motDePasse: "r4",
        nom: "Dream Bubble",
        prenom: "Dream Bubble",
        email: "dream bubble.dream bubble@example.com",
    },
    {
        id: 12353,
        role: "restaurateur",
        identifiant: "r5",
        motDePasse: "r5",
        nom: "Pralinette",
        prenom: "Pralinette",
        email: "pralinette.pralinette@example.com",
    },
    {
        id: 12354,
        role: "organisateur",
        identifiant: "o",
        motDePasse: "o",
        nom: "o",
        prenom: "o",
        email: "o.o@example.com",
    },
    {
        id: 12355,
        role: "organisateur",
        identifiant: "orga1",
        motDePasse: "orga1",
        nom: "orga1",
        prenom: "orga1",
        email: "orga1@gmail.com",
    },
    {
        id: 12356,
        role: "organisateur",
        identifiant: "orga2",
        motDePasse: "orga2",
        nom: "orga2",
        prenom: "orga2",
        email: "orga2@gmail.com",
    },
    {
        id: 12357,
        role: "organisateur",
        identifiant: "orga3",
        motDePasse: "orga3",
        nom: "orga3",
        prenom: "orga3",
        email: "orga3@gmail.com",
    },
    {
        id: 12358,
        role: "organisateur",
        identifiant: "orga4",
        motDePasse: "orga4",
        nom: "orga4",
        prenom: "orga4",
        email: "orga1@gmail.com",
    },
    {
        id: 12359,
        role: "organisateur",
        identifiant: "orga5",
        motDePasse: "orga5",
        nom: "orga5",
        prenom: "orga5",
        email: "orga5@gmail.com",
    },
    {
        id: 12360,
        role: "createur",
        identifiant: "c2",
        motDePasse: "c2",
        nom: "c2",
        prenom: "c2",
        email: "c2.c2@example.com",
    },
];
