export const jeux = [
    {
        _id: '01',
        type: 'Rapidité',
        name: 'Gobbit',
        image: require('@/assets/images/jeu_gobbit.png'),
        nombre_de_joueurs: [3, 4, 5, 6, 7, 8],
        age_minimum: 8,
        duree: 15,
        editeur: "Black Rock",
        nom_stand: ["stand1"],
        prix: "15",
    },
    {
        _id: '02',
        type: 'Stratégie',
        name: 'Voldétour',
        image: require('@/assets/images/jeu_voldetour.png'),
        nombre_de_joueurs: [2, 4],
        age_minimum: 7,
        duree: 30,
        editeur: "Black Rock",
        nom_stand: ["stand2"],
        prix: "30",
    },
    {
        _id: '03',
        type: 'Réflexion',
        name: 'Oyez Oyez',
        image: require('@/assets/images/jeu_oyezoyez.png'),
        nombre_de_joueurs: [2, 3, 4, 5, 6, 7, 8],
        age_minimum: 7,
        duree: 10,
        editeur: "Subverti",
        nom_stand: ["stand3"],
        prix: "10",
    },
    {
        _id: '04',
        type: 'Divertissement',
        name: 'Esquissé',
        image: require('@/assets/images/jeu_esquisse.png'),
        nombre_de_joueurs: [4, 5, 6, 7, 8],
        age_minimum: 8,
        duree: 30,
        editeur: "Goliath",
        nom_stand: ["stand1"],
        prix: "28",
    },
    {
        _id: '05',
        type: 'Stratégie',
        name: 'Saboteur',
        image: require('@/assets/images/jeu_saboteur.png'),
        nombre_de_joueurs: [3, 4, 5, 6, 7, 8, 9, 10],
        age_minimum: 8,
        duree: 60,
        editeur: "Gigamic",
        nom_stand: ["stand2"],
        prix: "15,50",
    },
    {
        _id: '06',
        type: 'Divertissement',
        name: 'Monique',
        image: require('@/assets/images/jeu_monique.png'),
        nombre_de_joueurs: [3, 4, 5, 6, 7, 8, 9, 10],
        age_minimum: 16,
        duree: 20,
        editeur: "Bakakou",
        nom_stand: ["stand2"],
        prix: "22",
    },
    {
        _id: '07',
        type: 'Reflexion',
        name: '6 qui prend',
        image: require('@/assets/images/jeu_6quiprend.png'),
        nombre_de_joueurs: [2, 3, 4, 5, 6, 7, 8, 9, 10],
        age_minimum: 10,
        duree: 45,
        editeur: "Amigo",
        nom_stand: ["stand3"],
        prix: "14",
    },
    {
        _id: '08',
        type: 'Bluff',
        name: 'Traitres à Bord',
        image: require('@/assets/images/jeu_traitresabord.png'),
        nombre_de_joueurs: [3, 4, 5, 6, 7, 8],
        age_minimum: 10,
        duree: 20,
        editeur: "Savana",
        nom_stand: ["stand1"],
        prix: "15",
    },
    {
        _id: '09',
        type: 'Rapidité',
        name: 'Dobble',
        image: require('@/assets/images/jeu_dobble.png'),
        nombre_de_joueurs: [2, 3, 4, 5, 6, 7, 8],
        age_minimum: 3,
        duree: 45,
        editeur: "Amigo",
        nom_stand: ["stand3"],
        prix: "17",
    },
];