export const points = [
    {
        idPoint: 1,
        category: 'Toilettes',
        name: 'Toilettes Publiques',
        coordinates: [46.647, -0.25235],
    },
    {
        idPoint: 2,
        category: 'Toilettes',
        name: 'Toilettes Publiques',
        coordinates: [46.649, -0.2523],
    },
    {
        idPoint: 3,
        category: 'Toilettes',
        name: 'Toilettes Publiques',
        coordinates: [46.64904, -0.25074],
    },
    {
        idPoint: 4,
        category: 'Toilettes',
        name: 'Toilettes Publiques',
        coordinates: [46.646255, -0.24848],
    },
    {
        idPoint: 5,
        category: 'Toilettes',
        name: 'Toilettes Publiques',
        coordinates: [46.6502, -0.2473],
    },
    {
        idPoint: 6,
        category: 'Toilettes',
        name: 'Toilettes Publiques',
        coordinates: [46.64585, -0.25125],
    },
    {
        idPoint: 7,
        category: 'Parking',
        name: 'Parking',
        coordinates: [46.645455, -0.25183],
    },
    {
        idPoint: 8,
        category: 'Tournois',
        name: 'Tournoi de Gobbit',
        coordinates: [46.647861, -0.247102],
    },
    {
        idPoint: 9,
        category: 'Tournois',
        name: 'Tournoi de Basketball',
        coordinates: [46.651968, -0.252591],
    },
    {
        idPoint: 10,
        category: 'Emplacement',
        disponible: false,
        coordinates: [46.647235, -0.24759],
    },
    {
        idPoint: 11,
        category: 'Emplacement',
        disponible: false,
        coordinates: [46.647987, -0.247901],
    },
    {
        idPoint: 12,
        category: 'Emplacement',
        disponible: false,
        coordinates: [46.645, -0.25],
    },
    {
        idPoint: 13,
        category: 'Emplacement',
        disponible: true,
        coordinates: [46.6472, -0.2479],
    },
    {
        idPoint: 14,
        category: 'Emplacement',
        disponible: true,
        coordinates: [46.6481, -0.2488],
    },
    {
        idPoint: 15,
        category: 'Emplacement',
        disponible: true,
        coordinates: [46.6483, -0.2516],
    },
];