export const tournois = [
    {
        _id: "000001",
        nom: "Molkky",
        prix: 5,
        lieu: "Domaine des loges",
        dates: [
            { annee: 2025, mois: 7, jour: 10, heures: 19, min: 0 },
            { annee: 2025, mois: 7, jour: 12, heures: 18, min: 30 },
            { annee: 2025, mois: 7, jour: 14, heures: 18, min: 0 },
        ],
        description: "Participez à un tournoi de Molkky, le célèbre jeu de quilles finlandaises. Venez tester votre adresse dans une ambiance conviviale.",
        prestataireId: 12344,
        placesLimite: 20,
        image: require('@/assets/images/tournois_molkky.png'),
    },
    {
        _id: "000002",
        nom: "Corn Hole",
        prix: 5,
        lieu: "Domaine des loges",
        dates: [
            { annee: 2025, mois: 7, jour: 9, heures: 19, min: 0 },
            { annee: 2025, mois: 7, jour: 11, heures: 18, min: 0 },
            { annee: 2025, mois: 7, jour: 13, heures: 17, min: 30 },
        ],
        description: "Affrontez d'autres participants dans un tournoi de Corn Hole. Le jeu consiste à lancer des sacs de maïs dans un trou pour marquer des points.",
        prestataireId: 12354,
        placesLimite: 15,
        image: require('@/assets/images/tournois_cornhole.png'),
    },
    {
        _id: "000003",
        nom: "Paintball",
        prix: 20,
        lieu: "Château de Parthenay",
        dates: [
            { annee: 2025, mois: 7, jour: 10, heures: 14, min: 0 },
            { annee: 2025, mois: 7, jour: 14, heures: 15, min: 30 },
            { annee: 2025, mois: 7, jour: 18, heures: 13, min: 0 },
        ],
        description: "Une bataille de paintball en équipe dans un cadre unique. Réservez vite vos places pour ce moment de fun et de stratégie.",
        prestataireId: 12355,
        placesLimite: 10,
        image: require('@/assets/images/tournois_paintball.png'),
    },
    {
        _id: "000004",
        nom: "Rocket League",
        prix: 5,
        lieu: "Palais des congrès",
        dates: [
            { annee: 2025, mois: 7, jour: 9, heures: 15, min: 0 },
            { annee: 2025, mois: 7, jour: 12, heures: 16, min: 30 },
            { annee: 2025, mois: 7, jour: 16, heures: 14, min: 0 },
        ],
        description: "Un tournoi e-sport de Rocket League pour les passionnés de jeux vidéo. Montrez vos compétences et devenez le champion de cette édition.",
        prestataireId: 12356,
        placesLimite: 30,
        image: require('@/assets/images/tournois_rocketleague.png'),
    },
    {
        _id: "000005",
        nom: "Escape Game",
        prix: 17,
        lieu: "Tour de la poudrière",
        dates: [
            { annee: 2025, mois: 7, jour: 10, heures: 14, min: 30 },
            { annee: 2025, mois: 7, jour: 13, heures: 15, min: 0 },
            { annee: 2025, mois: 7, jour: 17, heures: 16, min: 0 },
        ],
        description: "Mettez-vous au défi dans cet escape game spécialement conçu pour le festival. Résolvez les énigmes et échappez-vous avant le temps imparti.",
        prestataireId: 12357,
        placesLimite: 12,
        image: require('@/assets/images/tournois_escapegame.png'),
    },
    {
        _id: "000006",
        nom: "Basketball",
        prix: 3,
        lieu: "Place du drapeau",
        dates: [
            { annee: 2025, mois: 7, jour: 11, heures: 9, min: 0 },
            { annee: 2025, mois: 7, jour: 15, heures: 10, min: 30 },
            { annee: 2025, mois: 7, jour: 20, heures: 8, min: 0 },
        ],
        description: "Un tournoi de basketball 3 contre 3. Formez votre équipe et venez affronter les autres dans une ambiance sportive et festive.",
        prestataireId: 12358,
        placesLimite: 25,
        image: require('@/assets/images/tournois_basketball.png'),
    },
    {
        _id: "000007",
        nom: "Gobbit",
        prix: 5,
        lieu: "Place du drapeau",
        dates: [
            { annee: 2025, mois: 7, jour: 9, heures: 16, min: 0 },
            { annee: 2025, mois: 7, jour: 14, heures: 17, min: 30 },
            { annee: 2025, mois: 7, jour: 18, heures: 15, min: 0 },
        ],
        description: "Un tournoi du jeu de société Gobbit, où réflexes et observation sont de mise. Que le meilleur gagne !",
        prestataireId: 12359,
        placesLimite: 20,
        image: require('@/assets/images/tournois_gobbit.png'),
    },
];
